const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
  email: {
    type: String,
    required: true,
    unique: true,
    trim: true,
  },
  passwordHash: {
    type: String, // Will store the hash generated by bcryptjs
    required: true,
  },
  role: {
    type: String,
    required: true,
    enum: ['talent', 'seeker'],
  },
  name: {
    type: String,
    required: true,
  },
  // GeoJSON Object for location (fixed — no top-level `required: true`)
  location: {
    type: {
      type: String,
      enum: ['Point'],
      required: true,
      default: 'Point'
    },
    coordinates: {
      type: [Number], // [longitude, latitude]
      required: true,
    }
  },
  skills: [String],
  bio: String,
  profilePhotoUrl: String,
  avgRating: {
    type: Number,
    default: 0,
    min: 0,
    max: 5,
  },
  isVerified: {
    type: Boolean,
    required: true,
    default: false,
  },
}, { timestamps: true });

// IMPORTANT: Geospatial Index for proximity search
UserSchema.index({ location: '2dsphere' });

module.exports = mongoose.model('User', UserSchema);